config/routes.rb
Rails.application.routes.draw do
  #get 'static_pages/home'
  #match '/', to: 'static_pages#home', via: 'get'
  root to: 'static_pages#home'

  resources :part_types

  resources :parts do
    get 'part_names', :on => :collection
  end

  resources :costumes do
    get 'costume_names', :on => :collection
    get 'costume_parts', :on => :collection
  end

  resources :orders do
    get 'search', :on => :collection
    get 'update_order_in_rent_state', :on => :member
    get 'update_order_rent_returned_state', :on => :member
    #collection do
    #  get 'search'
    #end
  end

end

app/models/part.rb
class Part < ActiveRecord::Base
  has_and_belongs_to_many :costumes

  belongs_to :part_type

  validates :part_type_id, presence: true

  validates :name, presence: true, length: {maximum: 100},
                   uniqueness: {case_sensitive: false}
  validates :description, length: {maximum: 255}

  before_save {self.name = name.downcase}
end

app/models/part_type.rb
class PartType < ActiveRecord::Base
  has_many :parts, dependent: :destroy

  validates :type_name, presence: true, length: {maximum: 100},
                        uniqueness: {case_sensitive: false}

  before_save {self.type_name = type_name.downcase}
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update]

  def index
    @parts = Part.all
    @page_name = "Частини"
    @link_to_new = new_part_path
  end

  def show
  end

  def new
    @part = Part.new
    @page_name = "Нова частина"
  end

  def edit
    @page_name = "Редагуємо частину"
  end

  def part_names
    ord_date = make_normal_date
    ret_date = set_return_date

    # Schema how to guess if parts are booked for these dates
    #   26.01---------28.01
    #                         28.01------30.01
    # 25.01---27.01
    #         27.01----------------------30.01  <----- Parts already booked for these dates
    #         27.01------28.01
    #                    28.01-----29.01
    #                              29.01--------31.01
    #                                    30.01--31.01
    # 26.01-------------------------------------31.01

    order_ids = Order.where("(date >= ? AND date < ?) OR (return_date > ? AND return_date <= ?) OR (date < ? AND return_date > ?)",
                            ord_date, ret_date, ord_date, ret_date, ord_date, ret_date).pluck(:id)

    # Get booked parts for clients dates
    ordered_parts = order_ids.map { |oi| OrderedPart.where(order_id: oi).pluck(:ordered_part_id) }.flatten

    # While edit/update existed order, we show already exists parts for user
    # in case he will remove them from selected list he can pick them up again,
    # because they will be available for this order.
    if params[:already_selected_parts_ids] != ""
      ordered_parts = ordered_parts - ActiveSupport::JSON.decode(params[:already_selected_parts_ids])
    end

    parts = {}
    if params.has_key?(:name_pattern) and params[:name_pattern] != ""
      # Get available parts by name pattern for client dates and group them by part types.
      Part.where("name LIKE ? AND id NOT IN (?)", "%#{params[:name_pattern]}%", ordered_parts.empty? ? [0] : ordered_parts).group_by(&:part_type_id).each do |t_id, prts|
        parts[PartType.find(t_id).type_name] = prts.map {|p| p.id.to_s + ' ' + p.name + ' ' + p.description}
      end
    elsif params.has_key?(:id_pattern) and !(Integer(params[:id_pattern]) rescue nil).nil?
      # Get available part by id pattern for client dates and return part type with part.
      begin
        if !ordered_parts.include? params[:id_pattern].to_i
            prt = Part.find(params[:id_pattern])
            parts[PartType.find(prt.part_type_id).type_name] = [prt.id.to_s + ' ' + prt.name + ' ' + prt.description]
        end
      rescue ActiveRecord::RecordNotFound
        parts = {}
      end
    end

    if request.xhr?
      render :json => { :available_parts => parts }
    end
  end


  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to action: "index", notice: 'Part was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to action: "index", notice: 'Part was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_part
    @part = Part.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def part_params
    params.require(:part).permit(:name, :description, :part_type_id)
  end

  def set_return_date
    # Make return date base on selected date + number of days for rent
    make_normal_date + params[:rent_days].to_i.days
  end

  def make_normal_date
    # Make normal date YYYY-MM-DD based on list ["YYYY", "M", "D"]
    Date.new params[:ord_date][0].to_i, params[:ord_date][1].to_i, params[:ord_date][2].to_i
  end

end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_form.html.erb
<%= form_for(@part) do |f| %>
  <% if @part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
      <% @part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <% if @part.id.nil? %>
      <h4>Ідентифікатор нової частини буде - <%= Part.last.nil? ? 1 : Part.last.id + 1 %></h4>
    <% else %>
      <h4>Редагуємо частину з ідентифікатором - <%= @part.id %></h4>
    <% end %>
  </div>
  <br>
  <div class="field">
    <%= f.label "Частина" %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label "Опис" %><br>
    <%= f.text_field :description %>
  </div>
  <br>
  <div class="field">
    <%= f.label "Тип частини" %><br>
    <% PartType.all.each do |pt| %>
      <%= f.radio_button :part_type_id, pt.id %>
      <%= f.label "#{:part_type_id}_#{pt.id}", pt.type_name %>
    <% end %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Зберегти", :class => "btn btn-success" %>
    <%= link_to 'Відмінити', parts_path, { :class => "btn btn-default" } %>
  </div>
<% end %>

app/views/parts/edit.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/parts/index.html.erb
<div class="container">

  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Назва</th>
        <th>Опис</th>
        <th>Тип частини</th>
      </tr>
    </thead>

    <tbody>
    <% @parts.order('id DESC').each do |prt| %>
      <tr data-url="<%=edit_part_path(prt)%>">
        <td><%= prt.id %></td>
        <td><%= prt.name %></td>
        <td><%= prt.description %></td>
        <td><%= prt.part_type.type_name %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

</div>

app/views/parts/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>