config/routes.rb
Rails.application.routes.draw do
  #get 'static_pages/home'
  #match '/', to: 'static_pages#home', via: 'get'
  root to: 'static_pages#home'

  resources :part_types

  resources :parts do
    get 'part_names', :on => :collection
  end

  resources :costumes do
    get 'costume_names', :on => :collection
    get 'costume_parts', :on => :collection
  end

  resources :orders do
    get 'search', :on => :collection
    get 'update_order_in_rent_state', :on => :member
    get 'update_order_rent_returned_state', :on => :member
    #collection do
    #  get 'search'
    #end
  end

end

app/models/costume.rb
class Costume < ActiveRecord::Base
  has_and_belongs_to_many :parts

  validates :name, presence: true, length: {maximum: 100},
                   uniqueness: {case_sensitive: false}
  validates :description, length: {maximum: 255}

  before_save {self.name = name.downcase}
end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  before_action :set_costume, only: [:show, :edit, :update]

  def index
    @costumes = Costume.all
    @page_name = "Костюми"
    @link_to_new = new_costume_path
  end

  def show
  end

  def new
    @costume = Costume.new
    @page_name = "Новий костюм"
  end

  def edit
    @page_name = "Редагуємо костюм"
  end

  def costume_names
    cst_names = []
    puts "-----> #{params}"
    if params.has_key?(:name_pattern) and params[:name_pattern] != ""
      cst_names = Costume.where("name LIKE ?", "%#{params[:name_pattern]}%").map {|n| n.name}

    elsif params.has_key?(:id_pattern) and !(Integer(params[:id_pattern]) rescue nil).nil?
      begin
        cst_names = [Costume.find(params[:id_pattern].to_i).name]
      rescue ActiveRecord::RecordNotFound
        cst_names = []
      end
    end

    if request.xhr?
      render :json => { :cst_names => cst_names }
    end
  end

  def costume_parts
    ord_date = make_normal_date
    ret_date = set_return_date

    # Schema how to guess if parts are booked for these dates
    #   26.01---------28.01
    #                         28.01------30.01
    # 25.01---27.01
    #         27.01----------------------30.01  <----- Parts already booked for these dates
    #         27.01------28.01
    #                    28.01-----29.01
    #                              29.01--------31.01
    #                                    30.01--31.01
    # 26.01-------------------------------------31.01

    # Get order ids that match client dates
    order_ids = Order.where("(date >= ? AND date < ?) OR (return_date > ? AND return_date <= ?) OR (date < ? AND return_date > ?)",
                            ord_date, ret_date, ord_date, ret_date, ord_date, ret_date).pluck(:id)
    # Get booked parts for clients dates
    ordered_parts = order_ids.map { |oi| OrderedPart.where(order_id: oi).pluck(:ordered_part_id) }.flatten

    # While edit/update existed order, we show already exists parts for user
    # in case he will remove them from selected list he can pick them up again,
    # because they will be available for this order.
    if params[:already_selected_parts_ids] != ""
      ordered_parts = ordered_parts - ActiveSupport::JSON.decode(params[:already_selected_parts_ids])
    end

    parts = {}
    if params[:costume_name]
      # Get costume id by its name
      cst_id = Costume.where(name: params[:costume_name]).pluck(:id)[0]

      # Get available costume parts for client dates and group them by part types.
      Costume.find(cst_id).parts.where("id NOT IN (?)", ordered_parts.empty? ? [0] : ordered_parts).group_by(&:part_type_id).each do |t_id, cst_prts|
        parts[PartType.find(t_id).type_name] = cst_prts.map {|p| p.id.to_s + ' ' + p.name + ' ' + p.description}
      end
    end

    if request.xhr?
      render :json => { :available_parts => parts }
    end
  end

  def create
    @costume = Costume.new(costume_params)
    @parts = Part.where(:id => params[:costume_parts])
    @costume.parts << @parts

    respond_to do |format|
      if @costume.save
        format.html { redirect_to action: "index", notice: 'Costume was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @parts = Part.where(:id => params[:costume_parts])
    @costume.parts.destroy_all
    @costume.parts << @parts

    respond_to do |format|
      if @costume.update(costume_params)
        format.html { redirect_to action: "index", notice: 'Costume was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_costume
    @costume = Costume.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def costume_params
    params.require(:costume).permit(:name, :description)
  end

  def set_return_date
    # Make return date base on selected date + number of days for rent
    make_normal_date + params[:rent_days].to_i.days
  end

  def make_normal_date
    # Make normal date YYYY-MM-DD based on list ["YYYY", "M", "D"]
    Date.new params[:ord_date][0].to_i, params[:ord_date][1].to_i, params[:ord_date][2].to_i
  end

end

app/helpers/costumes_helper.rb
module CostumesHelper
end

app/views/costumes/_form.html.erb
<%= form_for(@costume) do |f| %>
  <% if @costume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@costume.errors.count, "error") %> prohibited this costume from being saved:</h2>

      <ul>
      <% @costume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <% if @costume.id.nil? %>
      <h4>Ідентифікатор нового костюму буде - <%= Costume.last.nil? ? 1 : Costume.last.id + 1 %></h4>
    <% else %>
      <h4>Редагуємо костюм з ідентифікатором - <%= @costume.id %></h4>
    <% end %>
  </div>
  <br>
  <div class="field">
    <%= f.label "Назва" %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label "Опис" %><br>
    <%= f.text_field :description %>
  </div>
  <br>
  <div class="field">
    <%= f.label "Частини костюма" %><br>
    <%= select_tag "costume_parts", options_from_collection_for_select(Part.all, 'id', 'name',@costume.parts.map{ |j| j.id }), :multiple => true %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Зберегти", :class => "btn btn-success" %>
    <%= link_to 'Відмінити', costumes_path, { :class => "btn btn-default" } %>
  </div>
<% end %>

app/views/costumes/edit.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/costumes/index.html.erb
<div class="container">

  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Назва</th>
        <th>Опис</th>
        <th>Частини</th>
      </tr>
    </thead>

    <tbody>
    <% @costumes.order('id DESC').each do |cst| %>
      <tr data-url="<%=edit_costume_path(cst)%>">
        <td><%= cst.id %></td>
        <td><%= cst.name %></td>
        <td><%= cst.description %></td>
        <td>
          <% cst.parts.each do |p| %>
            <dd><b><%= p.id.to_s %></b> <%= p.name %></dd>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

</div>

app/views/costumes/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>