config/routes.rb
Rails.application.routes.draw do
  #get 'static_pages/home'
  #match '/', to: 'static_pages#home', via: 'get'
  root to: 'static_pages#home'

  resources :part_types

  resources :parts do
    get 'part_names', :on => :collection
  end

  resources :costumes do
    get 'costume_names', :on => :collection
    get 'costume_parts', :on => :collection
  end

  resources :orders do
    get 'search', :on => :collection
    get 'update_order_in_rent_state', :on => :member
    get 'update_order_rent_returned_state', :on => :member
    #collection do
    #  get 'search'
    #end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :ordered_parts, dependent: :destroy

  validates :date, presence: true

  validates :return_date, presence: true

  validates :days_in_rent, presence: true, :inclusion => { :in => 1..100, :message => "Невірне значення для 'К-ть днів в прокаті'. Дозволено від 1 до 100 днів." }

  validates :name, presence: true, length: {maximum: 100}

  validates :tbd, length: {maximum: 255}

  validates :client_name, presence: true, length: {maximum: 100}
  validates :client_phone, presence: true, length: {is: 10}

  validates :reservation_fee, presence: true, :numericality => {:greater_than_or_equal_to => 0}
  validates :deposit_fee, presence: true, :numericality => {:greater_than_or_equal_to => 0}
  validates :rent_fee, presence: true, :numericality => {:greater_than_or_equal_to => 0}

  before_save {self.client_name = client_name.downcase}

  before_save {self.name = name.downcase}

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy,
                                   :update_order_in_rent_state,
                                   :update_order_rent_returned_state]
  before_action :check_if_selected_parts_not_already_ordered_for_create, only: :create
  before_action :check_if_selected_parts_not_already_ordered_for_update, only: :update

  def index
    @orders = Order.all
    @page_name = "Замовлення"
    @link_to_new = new_order_path
  end

  def show
    @page_name = "Сформоване Замовлення"
  end

  def search
    @rent_return = false
    if params[:date] then
      @orders = Order.all.where(:date => params[:date]).order('id DESC')
      @page_name = "Видача #{params[:date]}"
      @link_to_new = new_order_path(:chosen_date => params[:date])
    elsif params[:return_date] then
      @orders = Order.all.where(:return_date => params[:return_date]).order('id DESC')
      @page_name = "Здача #{params[:return_date]}"
      @rent_return = true
    end
  end

  def update_order_in_rent_state
    @order.in_rent = true
    respond_to do |format|
      if @order.save
        format.html { redirect_to search_orders_path(:date => params[:date]), notice: 'Order was successfully go in rent.' }
      else
        format.html { redirect_to search_orders_path(:date => params[:date]), warn: 'Order wasn\'t successfully go in rent.' }
      end
    end
  end

  def update_order_rent_returned_state
    @order.rent_returned = true
    respond_to do |format|
      if @order.save
        format.html { redirect_to search_orders_path(:return_date => params[:return_date]), notice: 'Order was successfully back from rent.' }
      else
        format.html { redirect_to search_orders_path(:return_date => params[:return_date]), warn: 'Order wasn\'t successfully back from rent.' }
      end
    end
  end

  def new
    @chosen_date = params[:chosen_date]
    @order = Order.new
    @page_name = "Нове Замовлення"
  end

  def edit
    @already_ord_parts = jsoned_already_ordered_parts
    @already_ord_parts_ids = jsoned_already_ordered_parts_ids
    @page_name = "Редагуємо Замовлення"
  end

  def create
    # Set from hidden tags because when element is disabled, rails doesn't send its value.
    params[:order][:date] = selected_date
    params[:order][:return_date] = set_return_date
    params[:order][:days_in_rent] = params[:h_days_in_rent]

    @order = Order.new(order_params)

    create_new_ordered_parts_for_order

    respond_to do |format|
      if @order.save && params[:sel_parts] != ""
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # Set from hidden tags because when element is disabled, rails doesn't send its value.
    params[:order][:date] = selected_date
    params[:order][:return_date] = set_return_date
    params[:order][:days_in_rent] = params[:h_days_in_rent]

    @already_ord_parts = jsoned_already_ordered_parts
    @already_ord_parts_ids = jsoned_already_ordered_parts_ids

    @order.ordered_parts.destroy_all

    create_new_ordered_parts_for_order

    respond_to do |format|
      if @order.update(order_params) && params[:sel_parts] != ""
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    begin
      @order = Order.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url, :flash => { :notice => "Record not found in db. Please refresh page to make it up to date." }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:date, :days_in_rent, :return_date,
                                  :name, :client_name, :client_phone,
                                  :tbd, :reservation_fee, :deposit_fee, :rent_fee)
  end

  def selected_date
    # Make normal date YYYY-MM-DD.
    Date.new params[:h_date_year].to_i, params[:h_date_month].to_i, params[:h_date_day].to_i
  end

  def set_return_date
    # Make return date base on selected date + number of days for rent
    selected_date + params[:h_days_in_rent].to_i.days
  end

  def jsoned_already_ordered_parts
    # Returns already ordered parts for selected order as [].to_json
    @order.ordered_parts.map {|i| i.ordered_part_id.to_s + ' ' + Part.find(i.ordered_part_id).name + ' ' + Part.find(i.ordered_part_id).description}.to_json
  end

  def jsoned_already_ordered_parts_ids
    # Returns already ordered parts ids for selected order as [].to_json
    @order.ordered_parts.pluck(:ordered_part_id).to_json
  end

  def create_new_ordered_parts_for_order
    # Create corresponding records in ordered_parts.
    decoded_ordered_parts_ids.each {|p| @order.ordered_parts.new(ordered_part_id: p)}
  end

  def decoded_ordered_parts_ids
    # Decode selected parts for order and return list of ids or empty list.
    if params[:sel_parts] != ""
      ActiveSupport::JSON.decode(params[:sel_parts]).map {|p| p.split(' ')[0].to_i}
    else
      []
    end
  end

  def check_if_selected_parts_not_already_ordered_for_create
    # Prevent booking of the same parts from different places simultaneously.
    # Get order ids that match client dates
    st_date = selected_date
    fin_date = set_return_date
    order_ids = Order.where("(date >= ? AND date < ?) OR (return_date > ? AND return_date <= ?) OR (date < ? AND return_date > ?)",
                            st_date, fin_date, st_date, fin_date, st_date, fin_date).pluck(:id)
    # Get booked parts ids for clients dates
    ordered_parts_ids = order_ids.map { |oi| OrderedPart.where(order_id: oi).pluck(:ordered_part_id) }.flatten
    puts "---1--> #{ordered_parts_ids}"
    puts "---111--> #{decoded_ordered_parts_ids}"
    if decoded_ordered_parts_ids.map {|i| ordered_parts_ids.include?(i) ? true : false}.any?
      puts "--2---> #{ordered_parts_ids}"
      redirect_to root_url, :flash => { :alert => "Somebody has already ordered these parts. Please try again." }
    end
  end

  def check_if_selected_parts_not_already_ordered_for_update
    # Prevent booking of the same parts from different places simultaneously.
    # Get order ids that match client dates
    st_date = selected_date
    fin_date = set_return_date
    order_ids = Order.where("(date >= ? AND date < ?) OR (return_date > ? AND return_date <= ?) OR (date < ? AND return_date > ?)",
                            st_date, fin_date, st_date, fin_date, st_date, fin_date).pluck(:id)
    # Get booked parts ids for clients dates
    ordered_parts_ids = order_ids.map { |oi| OrderedPart.where(order_id: oi).pluck(:ordered_part_id) }.flatten
    puts "---old--> #{ordered_parts_ids}"
    puts "---dec--> #{decoded_ordered_parts_ids}"
    puts "---@already_ord_parts_ids--> #{params[:already_selected_parts_ids]}"
    ordered_parts_ids = ordered_parts_ids - ActiveSupport::JSON.decode(params[:already_selected_parts_ids])
    puts "---new--> #{ordered_parts_ids}"
    if decoded_ordered_parts_ids.map {|i| ordered_parts_ids.include?(i) ? true : false}.any?
      puts "--2---> #{ordered_parts_ids}"
      redirect_to root_url, :flash => { :alert => "Somebody has already ordered these parts. Please try again." }
    end
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/edit.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/orders/index.html.erb
<div class="container">

  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Дата видачі</th>
        <th>Днів в прокаті</th>
        <th>Дата повернення</th>
        <th>Назва замовлення</th>
        <th>Обрані частини</th>
        <th>Клієнт</th>
        <th>Телефон</th>
        <th>Доробити</th>
        <th>Бронь</th>
        <th>Завдаток</th>
        <th>Вартість прокату</th>
        <th>Решта</th>
      </tr>
    </thead>

    <tbody>
    <% @orders.order('id DESC').each do |ord| %>
      <tr data-url="<%=edit_order_path(ord)%>">
        <td><%= ord.id %></td>
        <td><%= ord.date %></td>
        <td><%= ord.days_in_rent %></td>
        <td><%= ord.return_date %></td>
        <td><%= ord.name %></td>
        <td>
          <% ord.ordered_parts.each do |p| %>
            <li><b><%= p.ordered_part_id.to_s %></b> <%= Part.find(p.ordered_part_id).name + ' ' + Part.find(p.ordered_part_id).description %></li>
          <% end %>
        </td>
        <td><%= ord.client_name %></td>
        <td><%= ord.client_phone %></td>
        <td><%= ord.tbd %></td>
        <td><%= ord.reservation_fee %></td>
        <td><%= ord.deposit_fee %></td>
        <td><%= ord.rent_fee %></td>
        <td><%= ord.reservation_fee + ord.deposit_fee - ord.rent_fee %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

</div>

app/views/orders/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/orders/search.html.erb
<div class="container">

  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Дата видачі</th>
        <th>Днів в прокаті</th>
        <th>Дата повернення</th>
        <th>Назва замовлення</th>
        <th>Обрані частини</th>
        <th>Клієнт</th>
        <th>Телефон</th>
        <th>Доробити</th>
        <th>Бронь</th>
        <th>Завдаток</th>
        <th>Вартість прокату</th>
        <th>Решта</th>
        <% if @rent_return %>
          <th>Здати</th>
        <% else %>
          <th>Видати</th>
        <% end %>
      </tr>
    </thead>

    <tbody>
    <% if @rent_return %>
      <% @orders.where(:in_rent => true).each do |ord| %>
        <% if ord.rent_returned == false %>
          <tr data-url="<%=edit_order_path(ord)%>">
        <% elsif ord.rent_returned == true %>
          <tr class="success">
        <% end %>
            <td><%= ord.id %></td>
            <td><%= ord.date %></td>
            <td><%= ord.days_in_rent %></td>
            <td><%= ord.return_date %></td>
            <td><%= ord.name %></td>
            <td>
              <% ord.ordered_parts.each do |p| %>
                <li><b><%= p.ordered_part_id.to_s %></b> <%= Part.find(p.ordered_part_id).name + ' ' + Part.find(p.ordered_part_id).description %></li>
              <% end %>
            </td>
            <td><%= ord.client_name %></td>
            <td><%= ord.client_phone %></td>
            <td><%= ord.tbd %></td>
            <td><%= ord.reservation_fee %></td>
            <td><%= ord.deposit_fee %></td>
            <td><%= ord.rent_fee %></td>
            <td><%= ord.reservation_fee + ord.deposit_fee - ord.rent_fee %></td>
            <% if ord.rent_returned == false %>
              <td>
                <%= link_to update_order_rent_returned_state_order_path(ord, return_date: ord.return_date), { :class => "btn btn-lg btn-primary my-glyph-icon" } do %>
                  <span class="glyphicon glyphicon-log-in"></span>
                <% end %>
              </td>
            <% else %>
              <td></td>
            <% end %>
          </tr>
      <% end %>

    <% else %>
      <% @orders.each do |ord| %>
        <% if ord.in_rent == false %>
          <tr data-url="<%=edit_order_path(ord)%>">
        <% elsif ord.in_rent == true %>
          <tr class="success">
        <% end %>
            <td><%= ord.id %></td>
            <td><%= ord.date %></td>
            <td><%= ord.days_in_rent %></td>
            <td><%= ord.return_date %></td>
            <td><%= ord.name %></td>
            <td>
              <% ord.ordered_parts.each do |p| %>
                <li><b><%= p.ordered_part_id.to_s %></b> <%= Part.find(p.ordered_part_id).name + ' ' + Part.find(p.ordered_part_id).description %></li>
              <% end %>
            </td>
            <td><%= ord.client_name %></td>
            <td><%= ord.client_phone %></td>
            <td><%= ord.tbd %></td>
            <td><%= ord.reservation_fee %></td>
            <td><%= ord.deposit_fee %></td>
            <td><%= ord.rent_fee %></td>
            <td><%= ord.reservation_fee + ord.deposit_fee - ord.rent_fee %></td>
            <% if ord.in_rent == false %>
              <td>
                <%= link_to update_order_in_rent_state_order_path(ord, date: ord.date), { :class => "btn btn-lg btn-primary my-glyph-icon" } do %>
                  <span class="glyphicon glyphicon-log-out"></span>
                <% end %>
              </td>
            <% else %>
              <td></td>
            <% end %>
          </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>

</div>

app/views/orders/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <div class="panel panel-order-show panel-success centering">

    <div class="panel-heading">Замовлення # <strong><%= @order.id %></strong></div>

    <div class="panel-body">

      <table class="table table-striped">
        <tr>
          <th>Дата видачі:</th>
          <td><%= @order.date %></td>
        </tr>

        <tr>
          <th>К-ть днів:</th>
          <td><%=@order.days_in_rent%></td>
        </tr>

        <tr>
          <th>Дата повернення:</th>
          <td><%=@order.return_date%></td>
        </tr>

        <tr>
          <th>Назва замовлення:</th>
          <td><%=@order.name%></td>
        </tr>

        <tr>
          <th>Замовлені частини:</th>
          <td>
            <% @order.ordered_parts.each do |p| %>
              <li><b><%= p.ordered_part_id.to_s %></b> <%= Part.find(p.ordered_part_id).name + ' ' + Part.find(p.ordered_part_id).description %></li>
            <% end %>
          </td>
        </tr>

        <tr>
          <th>Клієнт:</th>
          <td><%=@order.client_name%></td>
        </tr>

        <tr>
          <th>Телефон:</th>
          <td><%= @order.client_phone %></td>
        </tr>

        <tr>
          <th>Доробити:</th>
          <td><%= @order.tbd %></td>
        </tr>

        <tr>
          <th>Бронь:</th>
          <td><%= @order.reservation_fee %></td>
        </tr>

        <tr>
          <th>Завдаток:</th>
          <td><%= @order.deposit_fee %></td>
        </tr>

        <tr>
          <th>Вартість прокату:</th>
          <td><%= @order.rent_fee %></td>
        </tr>

      </table>
    </div>

    <div class="panel-footer text-center">
      <%= link_to 'Редагувати', edit_order_url, { :class => "btn btn-warning malvina-action-button" } %>
      <%= link_to 'Видалити', @order, method: :delete, data: { confirm: 'Ви впевненні що хочете знищити це замовлення?'}, :class => "btn btn-danger malvina-action-button" %>
    </div>

  </div>

</div>