config/routes.rb
Rails.application.routes.draw do
  #get 'static_pages/home'
  #match '/', to: 'static_pages#home', via: 'get'
  root to: 'static_pages#home'

  resources :part_types

  resources :parts do
    get 'part_names', :on => :collection
  end

  resources :costumes do
    get 'costume_names', :on => :collection
    get 'costume_parts', :on => :collection
  end

  resources :orders do
    get 'search', :on => :collection
    get 'update_order_in_rent_state', :on => :member
    get 'update_order_rent_returned_state', :on => :member
    #collection do
    #  get 'search'
    #end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MalvinaApp</title>
    <style type="text/css">
      body{
        padding-top: 70px;
      }
    </style>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
    <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%#= render partial: "shared/flash_messages", flash: flash %>
  </head>

  <body>
  <nav role="navigation" class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="<%= root_url %>" class="navbar-brand"><%= image_tag("malv-icon.png", id: "logo") %></a></a>
      </div>
      <!-- Collection of nav links and other content for toggling -->
      <div id="navbarCollapse" class="collapse navbar-collapse">
        <% if !@page_name.nil? %>
          <ul class="nav navbar-nav navbar">
            <% if @link_to_new.nil? %>
              <li class="active"><a href="#"><b><%= @page_name %></b></a></li>
            <% else %>
              <li class="active dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#"><b><%= @page_name %></b> <b class="caret"></b></a>
                <ul role="menu" class="dropdown-menu">
                  <li><a href="<%= @link_to_new %>">Створити <%= @page_name %></a></li>
                </ul>
              </li>
            <% end %>
          </ul>
        <% end %>

        <form role="search" class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" id="search" placeholder="Пошук..." class="form-control">
          </div>
        </form>

        <ul class="nav navbar-nav navbar">
          <li><a href="<%= costumes_url %>"><b>Костюми</b></a></li>
          <li><a href="<%= parts_url %>"><b>Частини</b></a></li>
          <li><a href="<%= part_types_url %>"><b>Типи частин</b></a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><a href="<%= orders_url %>"><b>Замовлення</b></a></li>
          <a href="<%= root_url %>" class="navbar-brand"><%= image_tag("malv-icon.png", id: "logo") %></a>
        </ul>
      </div>
    </div>
  </nav>

  <%= yield %>

  </body>
</html>